from utility.headers import install_headers

Import('env')

staticScrAth = env.Library(
    'scrath',   # SCRyver mATH
    source=[
        # 'buffer.cpp',
    ]
)

headers = [
    'vector2d.hpp',
    'vector3d.hpp',
    'matrix4.hpp',
    'constants.hpp',
    'conversions.hpp',
    'transform3d.hpp',
]

inlines = [
    'vector2d.inl',
    'vector3d.inl',
    'matrix4_inl.hpp',
    'transform3d_inl.hpp',
]

install_headers(env, 'Scryver/Math', headers, inlines)
# @TODO: Implement copy-in file strategy for headers and inline/implementation

env.Install('$PREFIX/lib', staticScrAth)
