#!/bin/bash

BaseDir=`dirname "${BASH_SOURCE[0]}"`
OutputDir="$BaseDir/analysis/cppcheck"

cd "$OutputDir"

SourceDir="../../build"
GeneratedFile="cppcheck.txt"

cppcheck --enable=all \
         --library=../../cppcheck/opengl.cfg \
         --library=../../cppcheck/gtest.cfg \
         -rp="." \
         --suppress=missingIncludeSystem \
         --xml \
         "$SourceDir" 2> "$GeneratedFile"

cppcheck-htmlreport --report-dir="." --file="$GeneratedFile"
