Import('env')

sandboxEnv = env.Clone()
# clonedEnv.Append(LIBS=['grapher'])
# # For loading of shared libs set the origin
# clonedEnv.Append(LINKFLAGS = Split('-z origin'))
# # And set the exe to point to ../lib for shared libs
# clonedEnv.Append(RPATH = env.Literal(os.path.join('\\$$ORIGIN', os.pardir, 'lib')))

sandboxEnv['VERSION_MAJOR'] = 1
sandboxEnv['VERSION_MINOR'] = 0
sandboxEnv.Header('config')

sandboxEnv.Prepend(LIBS=['scrine', 'scruts', 'scring'])

main = sandboxEnv.Program('sandbox',
                          source=[
                              'main.cpp',
                          ])

env.Install('$PREFIX/bin', main)
