from utility.headers import install_headers
from SCons.Errors import UserError

name = 'scrogl'     # SCRyver OpenGL

try:
    Import('env')
    lib_dir = '$PREFIX/lib'
except UserError:
    Import('testEnv')
    env = testEnv
    name = 'test_' + name
    lib_dir = '$PREFIX/test/lib'

staticScrOgl = env.Library(
    name,
    source=[
        'manager.cpp',
        'shader.cpp',
    ],
)

headers = [
    'manager.hpp',
    'shader.hpp',
    'buffer.hpp',
]

inlines = [
    'buffer_inl.hpp',
    'manager_inl.hpp',
]

if 'testEnv' not in locals():
    install_headers(env, 'Scryver/OpenGL', headers, inlines)
# @TODO: Implement copy-in file strategy for headers and inline/implementation

env.Install(lib_dir, staticScrOgl)
