Import('testEnv')

mathEnv = testEnv.Clone()
mathEnv.Append(LIBS=['scrath'])

testScrAth = mathEnv.Program('testScrAth',
                    source=[
                        'test_vector2d.cpp',
                        'test_vector3d.cpp',
                        'test_vector_include.cpp',
                        'test_matrix4.cpp',
                        'test_conversions.cpp',
                        'test_transform.cpp',
                    ])

testEnv.Install('$PREFIX/test', testScrAth)
