from utility.headers import install_headers

Import('env')

staticScrIlity = env.Library(
    'scrility',   # SCRyver utILITY
    source=[
        # 'buffer.cpp',
    ]
)

headers = [
    'dictionary.hpp',
    'macros.hpp',
    'type_utils.hpp',
]

inlines = [
    'dictionary_inl.hpp',
]

install_headers(env, 'Scryver/Utility', headers, inlines)
# @TODO: Implement copy-in file strategy for headers and inline/implementation

env.Install('$PREFIX/lib', staticScrIlity)
env['scrility'] = staticScrIlity
