Import('testEnv')

utilEnv = testEnv.Clone()
utilEnv.Append(LIBS=['scriles'])

testScrIles = utilEnv.Program('testScrIles',
                              source=[
                                  'test_file_reader.cpp',
                              ])

testEnv.Install('$PREFIX/test', testScrIles)
testEnv.Install('$PREFIX/test/files', 'file_reader.txt')
testEnv.Install('$PREFIX/test/files', 'binary_file.txt')
