Import('testEnv')

openglEnv = testEnv.Clone()
openglEnv.Prepend(LIBS=['scrogl', 'scriles', 'scrine', 'scruts'])

testScrOgl = openglEnv.Program('testScrOgl',
                             source=[
                                 'test_shader.cpp',
                             ])

testEnv.Install('$PREFIX/test', testScrOgl)
testEnv.Install('$PREFIX/test/files', 'broken.glsl')
testEnv.Install('$PREFIX/test/files', 'vertex.glsl')
testEnv.Install('$PREFIX/test/files', 'fragment.glsl')
testEnv.Install('$PREFIX/test/files', 'linker_error.glsl')
