Import('testEnv')

openglEnv = testEnv.Clone()

openglEnv.Prepend(LIBS=['test_scrogl', 'scriles', 'scrine', 'scruts'])
testScrOgl = openglEnv.Program('testScrOgl',
                             source=[
                                 'glmock.cpp',
                                 'test_opengl_manager.cpp',
                                 'test_shader.cpp',
                                 'test_buffer.cpp',
                             ])

testEnv.Install('$PREFIX/test', testScrOgl)
testEnv.Install('$PREFIX/test/files', 'files/broken.glsl')
testEnv.Install('$PREFIX/test/files', 'files/vertex.glsl')
testEnv.Install('$PREFIX/test/files', 'files/fragment.glsl')
testEnv.Install('$PREFIX/test/files', 'files/linker_error.glsl')
